#!/bin/sh
USER=shostakovich
HOST=192.168.178.148
DIR=docker/data/rocu.de   # the directory where your web site files should go

hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR} # this will delete everything on the server that's not in the local public folder 

exit 0